# Generated by Django 2.2.5 on 2019-10-14 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191010_1820'),
    ]

    operations = [
        migrations.DeleteModel(
            name='select_food',
        ),
    ]
