# Generated by Django 2.2.5 on 2019-10-14 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('reg_no', models.IntegerField(default=0)),
                ('message', models.TextField(default='best')),
            ],
        ),
    ]
